// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capture} from '../models';
import {app} from '../models';
import {settings} from '../models';

export function AddDecryptBypass(arg1:string):Promise<void>;

export function AddQuickIgnore(arg1:string,arg2:string):Promise<boolean>;

export function BuildCurl(arg1:string,arg2:string):Promise<capture.CurlResult>;

export function ClearFlows():Promise<void>;

export function DeleteDomainGroup(arg1:string):Promise<void>;

export function ExportDomainGroup(arg1:string):Promise<string>;

export function ExportRules(arg1:boolean):Promise<string>;

export function FindFreePort(arg1:string,arg2:number):Promise<number>;

export function GetDomainGroupText(arg1:string):Promise<string>;

export function GetFlowBody(arg1:string,arg2:string):Promise<app.BodyPayload>;

export function GetFlowDetail(arg1:string):Promise<app.FlowDetail>;

export function GetFlowRawText(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetLocalAddrs():Promise<Array<string>>;

export function GetProxyStatus():Promise<app.ProxyStatus>;

export function GetSettings():Promise<settings.Settings>;

export function GetSystemProxyStatus():Promise<app.SystemProxyStatus>;

export function ImportDomainGroupFile(arg1:string):Promise<app.DomainGroupImportResult>;

export function ImportDomainGroupURL(arg1:string,arg2:string):Promise<app.DomainGroupImportResult>;

export function ImportDomainGroupsFromIndex(arg1:string,arg2:Array<string>,arg3:boolean):Promise<Array<app.IndexImportResult>>;

export function ImportRules(arg1:string):Promise<app.ImportRulesResult>;

export function InstallRootCA():Promise<void>;

export function ListDomainGroupDetails():Promise<Array<app.DomainGroupInfo>>;

export function ListDomainGroups():Promise<Record<string, any>>;

export function ListFlows():Promise<Array<app.FlowMeta>>;

export function ListSystemProcesses():Promise<Array<string>>;

export function ProbeURLImport(arg1:string):Promise<app.URLImportProbe>;

export function SaveDomainGroupText(arg1:string,arg2:string):Promise<app.DomainGroupImportResult>;

export function SaveSettings(arg1:settings.Settings):Promise<app.SaveSettingsResult>;

export function SendComposed(arg1:app.ComposedRequest):Promise<app.FlowDetail>;

export function SetFlowPinned(arg1:string,arg2:boolean):Promise<void>;

export function SetSystemProxy(arg1:boolean):Promise<void>;

export function StartProxy(arg1:string):Promise<void>;

export function StopProxy():Promise<void>;
