// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ctlapi} from '../models';
import {app} from '../models';
import {capture} from '../models';
import {settings} from '../models';
import {persist} from '../models';
import {jsontext} from '../models';

export function AIChatStart(arg1:ctlapi.AIChatRequest):Promise<app.AIChatHandle>;

export function AIChatStop(arg1:app.AIChatHandle):Promise<void>;

export function AITestConn():Promise<Record<string, any>>;

export function AdbClearProxy(arg1:string,arg2:string):Promise<string>;

export function AdbSetProxy(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AdbTest(arg1:string):Promise<string>;

export function AddDecryptBypass(arg1:string):Promise<void>;

export function AddQuickIgnore(arg1:string,arg2:string):Promise<boolean>;

export function BuildCurl(arg1:string,arg2:string):Promise<capture.CurlResult>;

export function ClearFlows():Promise<void>;

export function CloseProject():Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<settings.ProjectMeta>;

export function DeleteDomainGroup(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteTagApp(arg1:string,arg2:boolean):Promise<number>;

export function ExportDomainGroup(arg1:string):Promise<string>;

export function ExportRules(arg1:boolean):Promise<string>;

export function FetchAIModels(arg1:settings.AIConfig):Promise<app.AIModelsResult>;

export function FindFreePort(arg1:string,arg2:number):Promise<number>;

export function GetAIConfigApp():Promise<app.AIConfigView>;

export function GetAIConfigView():Promise<Record<string, any>>;

export function GetCurrentProject():Promise<settings.ProjectMeta>;

export function GetDomainGroupText(arg1:string):Promise<string>;

export function GetFlowBody(arg1:string,arg2:string):Promise<app.BodyPayload>;

export function GetFlowDetail(arg1:string):Promise<app.FlowDetail>;

export function GetFlowRawText(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetLocalAddrs():Promise<Array<string>>;

export function GetProxyStatus():Promise<app.ProxyStatus>;

export function GetReviewURL():Promise<string>;

export function GetSettings():Promise<app.SettingsView>;

export function GetSystemProxyStatus():Promise<app.SystemProxyStatus>;

export function ImportDomainGroupFile(arg1:string):Promise<app.DomainGroupImportResult>;

export function ImportDomainGroupURL(arg1:string,arg2:string):Promise<app.DomainGroupImportResult>;

export function ImportDomainGroupsFromIndex(arg1:string,arg2:Array<string>,arg3:boolean):Promise<Array<app.IndexImportResult>>;

export function ImportRules(arg1:string):Promise<app.ImportRulesResult>;

export function InstallRootCA():Promise<void>;

export function ListDomainGroupDetails():Promise<Array<app.DomainGroupInfo>>;

export function ListDomainGroups():Promise<Record<string, any>>;

export function ListFlows():Promise<Array<app.FlowMeta>>;

export function ListProjects():Promise<Array<settings.ProjectMeta>>;

export function ListSystemProcesses():Promise<Array<string>>;

export function ListTags():Promise<Array<app.TagInfo>>;

export function PickAdbPath():Promise<string>;

export function ProbeURLImport(arg1:string):Promise<app.URLImportProbe>;

export function RenameProject(arg1:string,arg2:string):Promise<void>;

export function RenameTagApp(arg1:string,arg2:string):Promise<void>;

export function ReviewAddIgnore(arg1:string,arg2:string,arg3:string):Promise<persist.ReviewIgnore>;

export function ReviewDeleteIgnore(arg1:string,arg2:string):Promise<boolean>;

export function ReviewFlowBody(arg1:string,arg2:string):Promise<app.BodyPayload>;

export function ReviewFlowDetail(arg1:string):Promise<app.FlowDetail>;

export function ReviewFlowList(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:persist.ReviewListOpts):Promise<Array<app.FlowMeta>>;

export function ReviewHistogram(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<number>;

export function ReviewListIgnores():Promise<Array<persist.ReviewIgnore>>;

export function ReviewTagsOverview():Promise<Array<app.TagInfo>>;

export function SaveAIConfigApp(arg1:string):Promise<app.AIConfigView>;

export function SaveAIConfigPatch(arg1:jsontext.Value):Promise<Record<string, any>>;

export function SaveDomainGroupText(arg1:string,arg2:string):Promise<app.DomainGroupImportResult>;

export function SaveSettings(arg1:app.SettingsView):Promise<app.SaveSettingsResult>;

export function SendComposed(arg1:app.ComposedRequest):Promise<app.FlowDetail>;

export function SetFlowPinned(arg1:string,arg2:boolean):Promise<void>;

export function SetSystemProxy(arg1:boolean):Promise<void>;

export function StartProxy(arg1:string):Promise<void>;

export function StopProxy():Promise<void>;

export function SwitchProject(arg1:string):Promise<void>;

export function TagFlows(arg1:Array<string>,arg2:string,arg3:boolean):Promise<app.TagResult>;

export function TestAIConnection(arg1:settings.AIConfig):Promise<app.AITestResult>;

export function WailsAddIgnore(arg1:string,arg2:string,arg3:string):Promise<app.WailsAddIgnoreResult>;

export function WailsFlowList(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:persist.ReviewListOpts):Promise<app.WailsFlowListResult>;

export function WailsHistogram(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<app.WailsHistogramResult>;

export function WailsTagsOverview():Promise<app.WailsTagsOverview>;
