// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdbClearProxy(arg1, arg2) {
  return window['go']['app']['App']['AdbClearProxy'](arg1, arg2);
}

export function AdbSetProxy(arg1, arg2, arg3) {
  return window['go']['app']['App']['AdbSetProxy'](arg1, arg2, arg3);
}

export function AdbTest(arg1) {
  return window['go']['app']['App']['AdbTest'](arg1);
}

export function AddDecryptBypass(arg1) {
  return window['go']['app']['App']['AddDecryptBypass'](arg1);
}

export function AddQuickIgnore(arg1, arg2) {
  return window['go']['app']['App']['AddQuickIgnore'](arg1, arg2);
}

export function BuildCurl(arg1, arg2) {
  return window['go']['app']['App']['BuildCurl'](arg1, arg2);
}

export function ClearFlows() {
  return window['go']['app']['App']['ClearFlows']();
}

export function CloseProject() {
  return window['go']['app']['App']['CloseProject']();
}

export function CreateProject(arg1, arg2) {
  return window['go']['app']['App']['CreateProject'](arg1, arg2);
}

export function DeleteDomainGroup(arg1) {
  return window['go']['app']['App']['DeleteDomainGroup'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function DeleteTagApp(arg1, arg2) {
  return window['go']['app']['App']['DeleteTagApp'](arg1, arg2);
}

export function ExportDomainGroup(arg1) {
  return window['go']['app']['App']['ExportDomainGroup'](arg1);
}

export function ExportRules(arg1) {
  return window['go']['app']['App']['ExportRules'](arg1);
}

export function FindFreePort(arg1, arg2) {
  return window['go']['app']['App']['FindFreePort'](arg1, arg2);
}

export function GetCurrentProject() {
  return window['go']['app']['App']['GetCurrentProject']();
}

export function GetDomainGroupText(arg1) {
  return window['go']['app']['App']['GetDomainGroupText'](arg1);
}

export function GetFlowBody(arg1, arg2) {
  return window['go']['app']['App']['GetFlowBody'](arg1, arg2);
}

export function GetFlowDetail(arg1) {
  return window['go']['app']['App']['GetFlowDetail'](arg1);
}

export function GetFlowRawText(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFlowRawText'](arg1, arg2, arg3);
}

export function GetLocalAddrs() {
  return window['go']['app']['App']['GetLocalAddrs']();
}

export function GetProxyStatus() {
  return window['go']['app']['App']['GetProxyStatus']();
}

export function GetReviewURL() {
  return window['go']['app']['App']['GetReviewURL']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetSystemProxyStatus() {
  return window['go']['app']['App']['GetSystemProxyStatus']();
}

export function ImportDomainGroupFile(arg1) {
  return window['go']['app']['App']['ImportDomainGroupFile'](arg1);
}

export function ImportDomainGroupURL(arg1, arg2) {
  return window['go']['app']['App']['ImportDomainGroupURL'](arg1, arg2);
}

export function ImportDomainGroupsFromIndex(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportDomainGroupsFromIndex'](arg1, arg2, arg3);
}

export function ImportRules(arg1) {
  return window['go']['app']['App']['ImportRules'](arg1);
}

export function InstallRootCA() {
  return window['go']['app']['App']['InstallRootCA']();
}

export function ListDomainGroupDetails() {
  return window['go']['app']['App']['ListDomainGroupDetails']();
}

export function ListDomainGroups() {
  return window['go']['app']['App']['ListDomainGroups']();
}

export function ListFlows() {
  return window['go']['app']['App']['ListFlows']();
}

export function ListProjects() {
  return window['go']['app']['App']['ListProjects']();
}

export function ListSystemProcesses() {
  return window['go']['app']['App']['ListSystemProcesses']();
}

export function ListTags() {
  return window['go']['app']['App']['ListTags']();
}

export function PickAdbPath() {
  return window['go']['app']['App']['PickAdbPath']();
}

export function ProbeURLImport(arg1) {
  return window['go']['app']['App']['ProbeURLImport'](arg1);
}

export function RenameProject(arg1, arg2) {
  return window['go']['app']['App']['RenameProject'](arg1, arg2);
}

export function RenameTagApp(arg1, arg2) {
  return window['go']['app']['App']['RenameTagApp'](arg1, arg2);
}

export function ReviewFlowBody(arg1, arg2) {
  return window['go']['app']['App']['ReviewFlowBody'](arg1, arg2);
}

export function ReviewFlowDetail(arg1) {
  return window['go']['app']['App']['ReviewFlowDetail'](arg1);
}

export function ReviewFlowList(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReviewFlowList'](arg1, arg2, arg3);
}

export function SaveDomainGroupText(arg1, arg2) {
  return window['go']['app']['App']['SaveDomainGroupText'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SendComposed(arg1) {
  return window['go']['app']['App']['SendComposed'](arg1);
}

export function SetFlowPinned(arg1, arg2) {
  return window['go']['app']['App']['SetFlowPinned'](arg1, arg2);
}

export function SetSystemProxy(arg1) {
  return window['go']['app']['App']['SetSystemProxy'](arg1);
}

export function StartProxy(arg1) {
  return window['go']['app']['App']['StartProxy'](arg1);
}

export function StopProxy() {
  return window['go']['app']['App']['StopProxy']();
}

export function SwitchProject(arg1) {
  return window['go']['app']['App']['SwitchProject'](arg1);
}

export function TagFlows(arg1, arg2, arg3) {
  return window['go']['app']['App']['TagFlows'](arg1, arg2, arg3);
}
