// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDecryptBypass(arg1) {
  return window['go']['main']['App']['AddDecryptBypass'](arg1);
}

export function AddQuickIgnore(arg1, arg2) {
  return window['go']['main']['App']['AddQuickIgnore'](arg1, arg2);
}

export function BuildCurl(arg1, arg2) {
  return window['go']['main']['App']['BuildCurl'](arg1, arg2);
}

export function ClearFlows() {
  return window['go']['main']['App']['ClearFlows']();
}

export function DeleteDomainGroup(arg1) {
  return window['go']['main']['App']['DeleteDomainGroup'](arg1);
}

export function ExportDomainGroup(arg1) {
  return window['go']['main']['App']['ExportDomainGroup'](arg1);
}

export function ExportRules(arg1) {
  return window['go']['main']['App']['ExportRules'](arg1);
}

export function FindFreePort(arg1, arg2) {
  return window['go']['main']['App']['FindFreePort'](arg1, arg2);
}

export function GetDomainGroupText(arg1) {
  return window['go']['main']['App']['GetDomainGroupText'](arg1);
}

export function GetFlowBody(arg1, arg2) {
  return window['go']['main']['App']['GetFlowBody'](arg1, arg2);
}

export function GetFlowDetail(arg1) {
  return window['go']['main']['App']['GetFlowDetail'](arg1);
}

export function GetFlowRawText(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFlowRawText'](arg1, arg2, arg3);
}

export function GetLocalAddrs() {
  return window['go']['main']['App']['GetLocalAddrs']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemProxyStatus() {
  return window['go']['main']['App']['GetSystemProxyStatus']();
}

export function ImportDomainGroupFile(arg1) {
  return window['go']['main']['App']['ImportDomainGroupFile'](arg1);
}

export function ImportDomainGroupURL(arg1, arg2) {
  return window['go']['main']['App']['ImportDomainGroupURL'](arg1, arg2);
}

export function ImportDomainGroupsFromIndex(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportDomainGroupsFromIndex'](arg1, arg2, arg3);
}

export function ImportRules(arg1) {
  return window['go']['main']['App']['ImportRules'](arg1);
}

export function InstallRootCA() {
  return window['go']['main']['App']['InstallRootCA']();
}

export function ListDomainGroupDetails() {
  return window['go']['main']['App']['ListDomainGroupDetails']();
}

export function ListDomainGroups() {
  return window['go']['main']['App']['ListDomainGroups']();
}

export function ListFlows() {
  return window['go']['main']['App']['ListFlows']();
}

export function ListSystemProcesses() {
  return window['go']['main']['App']['ListSystemProcesses']();
}

export function ProbeURLImport(arg1) {
  return window['go']['main']['App']['ProbeURLImport'](arg1);
}

export function SaveDomainGroupText(arg1, arg2) {
  return window['go']['main']['App']['SaveDomainGroupText'](arg1, arg2);
}

export function SendComposed(arg1) {
  return window['go']['main']['App']['SendComposed'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetFlowPinned(arg1, arg2) {
  return window['go']['main']['App']['SetFlowPinned'](arg1, arg2);
}

export function SetSystemProxy(arg1) {
  return window['go']['main']['App']['SetSystemProxy'](arg1);
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
