// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDecryptBypass(arg1) {
  return window['go']['main']['App']['AddDecryptBypass'](arg1);
}

export function ClearFlows() {
  return window['go']['main']['App']['ClearFlows']();
}

export function GetFlowBody(arg1, arg2) {
  return window['go']['main']['App']['GetFlowBody'](arg1, arg2);
}

export function GetFlowDetail(arg1) {
  return window['go']['main']['App']['GetFlowDetail'](arg1);
}

export function GetLocalAddrs() {
  return window['go']['main']['App']['GetLocalAddrs']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemProxyStatus() {
  return window['go']['main']['App']['GetSystemProxyStatus']();
}

export function InstallRootCA() {
  return window['go']['main']['App']['InstallRootCA']();
}

export function ListDomainGroups() {
  return window['go']['main']['App']['ListDomainGroups']();
}

export function ListFlows() {
  return window['go']['main']['App']['ListFlows']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetSystemProxy(arg1) {
  return window['go']['main']['App']['SetSystemProxy'](arg1);
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
